DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id`   INT(20)     NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `age`  INT(10)     NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

DELETE FROM `user`;
